# Generated by Django 3.0.6 on 2020-05-07 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('orderDiscount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('email', models.EmailField(max_length=256)),
                ('deliveryFirstName', models.CharField(max_length=30)),
                ('deliveryLastName', models.CharField(max_length=30)),
                ('deliveryCompany', models.CharField(blank=True, max_length=50, null=True)),
                ('deliveryMethod', models.CharField(max_length=50)),
                ('deliveryPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deliveryStreet', models.CharField(max_length=256)),
                ('deliveryStreetNum', models.CharField(max_length=20)),
                ('deliveryCity', models.CharField(max_length=256)),
                ('deliveryPostal', models.CharField(max_length=10)),
                ('deliveryCountry', models.CharField(max_length=256)),
                ('deliveryPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('billingFirstName', models.CharField(max_length=30)),
                ('billingLastName', models.CharField(max_length=30)),
                ('billingCompany', models.CharField(blank=True, max_length=50, null=True)),
                ('billingStreet', models.CharField(max_length=256)),
                ('billingStreetNum', models.CharField(max_length=20)),
                ('billingCity', models.CharField(max_length=256)),
                ('billingPostal', models.CharField(max_length=10)),
                ('billingCountry', models.CharField(max_length=256)),
                ('billingPhone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Game', 'Video game'), ('Console', 'Console'), ('Misc', 'Misc.')], max_length=50)),
                ('manufacturer', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/media/product_img/')),
                ('thumbnail', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('displayOrder', models.SmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemDiscount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('quantity', models.SmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='store_app.OrderItem', to='store_app.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
