# Generated by Django 3.0.6 on 2020-05-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSeller',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('copies_sold', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
