# Generated by Django 3.0.6 on 2020-05-07 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_auto_20200506_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billingCity',
            field=models.CharField(default='Reykjavik', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billingCompany',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billingCountry',
            field=models.CharField(default='Iceland', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billingFirstName',
            field=models.CharField(default='John', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billingLastName',
            field=models.CharField(default='Johnson', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billingPhone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billingPostal',
            field=models.CharField(default='101', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billingStreet',
            field=models.CharField(default='Laugavegur', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='billingStreetNum',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryCity',
            field=models.CharField(default='Reykjavik', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryCompany',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryCountry',
            field=models.CharField(default='Iceland', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryFirstName',
            field=models.CharField(default='John', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryLastName',
            field=models.CharField(default='Johnson', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryPhone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryPostal',
            field=models.CharField(default='101', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryStreet',
            field=models.CharField(default='Laugavegur', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryStreetNum',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='john.johnson@gmail.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
