# Generated by Django 3.0.6 on 2020-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(default='Playstation 2', max_length=100),
            preserve_default=False,
        ),
    ]
