# Generated by Django 3.0.6 on 2020-05-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_auto_20200507_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryMethod',
            field=models.CharField(default='Express', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryPrice',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
    ]
