# Generated by Django 3.0.6 on 2020-05-06 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_app', '0001_initial'),
        ('shopping_cart_app', '0001_initial'),
        ('profile_app', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='searchProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.Product'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='searchProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='postal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.Postal'),
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='profile',
            name='searches',
            field=models.ManyToManyField(through='profile_app.SearchHistory', to='store_app.Product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shoppingCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart_app.ShoppingCart'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
