# Generated by Django 3.0.6 on 2020-05-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_app', '0001_initial'),
        ('profile_app', '0002_auto_20200506_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shoppingCart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart_app.ShoppingCart'),
        ),
    ]
